### ISSUE TITLE
TODO RNF8

### ISSUE THREAD

**Issue by tico19** [geek0x90/SCRUM#1]
Verifica la [RNF8](https://github.com/geek0x90/SCRUM/blob/master/Requisiti%20Non%20Funzionali.md#rnf8) a chi vuoi attribuire la dipendenza, [RNF3](https://github.com/geek0x90/SCRUM/blob/master/Requisiti%20Non%20Funzionali.md#rnf3) o [RNF5](https://github.com/geek0x90/SCRUM/blob/master/Requisiti%20Non%20Funzionali.md#rnf5)
Il file è: [Requisiti Non Funzionali](https://github.com/geek0x90/SCRUM/blob/master/Requisiti%20Non%20Funzionali.md)

**Comment by geek0x90** [comment]
Fatto :)
